dist: trusty
language: rust
services: docker
sudo: required

rust:
  - nightly
  - stable
  # MSRV
  - 1.38.0

env: TARGET=x86_64-unknown-linux-gnu

install:
  - sh ci/install.sh
  - source ~/.cargo/env || true

script:
  - sh ci/script.sh

cache: cargo
before_cache:
  - chmod -R a+r $HOME/.cargo

branches:
  only:
    - staging
    - trying

notifications:
  email:
    on_success: never
